---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ctrlplane
  namespace: argocd
spec:
  project: servicemesh
  source:
    repoURL: https://github.com/mcaimi/ocp4-argocd.git
    targetRevision: HEAD
    path: servicemesh/controlplane
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
