apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
commonLabels:
  app: istio
  kind: controlplane
  master: argocd-application

resources:
  - project.yaml
  - controlplane.yaml
