apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knative-eventing
commonLabels:
  app: knative
  kind: eventing
  master: argocd-application

resources:
  - namespace.yaml
  - eventing.yaml
