apiVersion: v1
data:
  htpasswd: ZGV2ZWxvcGVyOiQyeSQwNSR5c2h2cy9keElsaWFGSkdQbHZocHVlWE0wTXczQWVyLjI5UkM2WklqL0xzbUpvWXJXdnMyMgpsb2NhbGFkbWluOiQyeSQwNSQ0ZkJ5MXJ4cFZSck14QjR5SnZ6ckhPTUZibm5BZGxLcGpwdzFDVlR5RFFzY0NRbjNPM1pGYQo=
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
type: Opaque
