apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-config
commonLabels:
  app: oc
  kind: cluster-configuration
  master: argocd-application

resources:
  - htpasswd-secret.yaml
  - oauth-provider.yaml
  - cluster-role-binding.yaml
