---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-rbac
  namespace: argocd
spec:
  project: argocd-infra
  source:
    repoURL: https://github.com/mcaimi/ocp4-argocd.git
    targetRevision: HEAD
    path: argocd/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-operator
  namespace: argocd
spec:
  project: argocd-infra
  source:
    repoURL: https://github.com/mcaimi/ocp4-argocd.git
    targetRevision: HEAD
    path: argocd/operator
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-cluster
  namespace: argocd
spec:
  project: argocd-infra
  source:
    repoURL: https://github.com/mcaimi/ocp4-argocd.git
    targetRevision: HEAD
    path: argocd/cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
