---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-controller
  namespace: argocd
spec:
  applicationInstanceLabelKey: redhat.com/argocd-controller
  usersAnonymousEnabled: false
  ha:
    enabled: true
  dex:
    image: quay.io/redhat-cop/dex
    version: v2.22.0-openshift
    openShiftOAuth: true
  grafana:
    enabled: true
    route: true
  prometheus:
    enabled: true
    route: true
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
      g, argocd-users, role:readonly
      g, argocd-admins, role:admin
    scopes: '[groups]'
  server:
    enabled: true
    route: true
    autoscale:
      enabled: true
      hpa:
        maxReplicas: 3
        minReplicas: 2
        scaleTargetRef:
          apiVersion: extensions/v1beta1
          kind: Deployment
          name: argocd-controller-server
        targetCPUUtilizationPercentage: 50
