---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: camel-k-operator
  namespace: camelknative
  annotations:
    olm.operatorGroup: camelk-operatorgroup
spec:
  channel: "stable"
  installPlanApproval: "Automatic"
  source: "community-operators" 
  sourceNamespace: "openshift-marketplace"
  name: "camel-k"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: knative-camel-operator
  namespace: openshift-operators
spec:
  channel: "alpha"
  installPlanApproval: "Automatic"
  source: "community-operators" 
  sourceNamespace: "openshift-marketplace"
  name: "knative-camel-operator"
