apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
commonLabels:
  app: knative
  kind: operator
  master: argocd-application

resources:
  - project.yaml
  - knative.yaml
