apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: camel-k
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
