apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knative-serving
commonLabels:
  app: knative
  kind: serving
  master: argocd-application

resources:
  - namespace.yaml
  - serving.yaml
